apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: crm-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vishalab26/crm-devops-project
    targetRevision: HEAD
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
